require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new('spec')

task :default => :spec

task :all => [:spec, :generate_report]

def generate_report
  puts "Generating report"
  system("allure generate -c gen/allure-results -o allure-report")
  system("allure open")
end

task :generate_report do
    puts "Generating reports"
    generate_report
end
